### ISSUE TITLE
Support for npm specifiers

### ISSUE THREAD

**Issue by seangenabe** [micheledurante/esbuild-plugin-deno-remote-import#1]
npm specifiers support has been released -- https://deno.land/manual@v1.28.2/node/npm_specifiers#using-npm-packages-with-npm-specifiers

Please consider supporting them.

**Comment by micheledurante** [comment]
Hi, thanks for the pointer, published on NPM at https://www.npmjs.com/package/esbuild-plugin-deno-remote-import
